name: 'Compile and install HAProxy'
description: 'Compiles and installs HAProxy into the PATH.'
author: 'Tim Düsterhus'
inputs:
  branch:
    required: true
    description: 'HAProxy branch to install.'
  use_lua:
    required: false
    default: 'false'
    description: 'Compile with Lua support.'
  use_openssl:
    required: false
    default: 'false'
    description: 'Compile with SSL support.'
outputs:
  version:
    description: 'The exact HAProxy version that was installed.'
runs:
  using: 'node12'
  main: 'dist/index.js'
